## Basic Configuration
baseurl = "/"
languageCode = "en"

title = "jdkato.io"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

summarylength = 30

# paginate = 5

## Site Settings
[params]
    author = "jdkato"
    description = ""
    authorimage = "img/me.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "jdkato"
    keybase = "jdkato"
    reddit = "jdkato"
    email = "joseph@jdkato.io"
    strava = "33348244"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"


[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "posts"
    url = "/posts/"

# [[menu.main]]
#     name = "Portfolio"
#     identifier = "portfolio"
#     weight = 200
#     url = "/portfolio/"
